import { GetStaticProps } from 'next';
import Head from 'next/head'
import { Flex, Heading } from '@chakra-ui/react'
import { Banner } from '../components/Banner';
import { Header } from '../components/Header'
import { TravelTypes } from '../components/TravelTypes'
import { Divider } from '../components/Divider';
import { Slider } from '../components/Slider';
import api from '../services/api';

interface HomeProps {
  continents: {
    imageUrl: string;
    linkUrl: string;
    linkTitle: string;
    linkSubTitle: string;
  }[]
}

export default function Home({continents} : HomeProps ) {
  return (
    <div>
      <Head>
        <title>World-Trip | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Flex direction="column">
          <Header />
          <Banner />
          <TravelTypes />
          <Divider />
          <Heading
            textAlign="center"
            fontWeight="600"
            mb={["5", "14"]}
            fontSize={["lg", "3xl", "4xl"]}
          >
            Vamos nessa? <br /> Então escolha seu continente.
          </Heading>
          <Slider continents={continents}/> 
        </Flex>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const response = await api.get('/continents');
  const continents = response.data;
  
  return {
    props: {
      continents
    }
  }
}
